adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.login, name='login')
]

studentapp/urls.py
from django.urls import path
from . import views

app_name = 'studentapp'

urlpatterns = [
    path('login/', views.login, name='login')
]

studentportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('student/', include('studentapp.urls'))
]

adminapp/models.py
from django.db import models

# Create your models here.

studentapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage/homepage.html')

def login(request):
    return render(request, 'index.html', context={
        "title": "Admin Login"
    })

studentapp/views.py
from django.shortcuts import render

def login(request):
    return render(request, 'index.html', context={
        "title": "Student Login",
    })

adminapp/templates/homepage/homepage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/styles.css' %}">
</head>
<body>
    <h1>Hello Dashboard</h1>
    <button onclick="location.href='{% url 'adminapp:login' %}'" type="button">Sign in for Admin</button>
    <button onclick="location.href='{% url 'studentapp:login' %}'" type="button">Sign in for Student</button>
</body>
</html>

adminapp/templates/index.html
<h1>
    {{title}}!
</h1>

studentapp/templates/index.html
<h1>
    {{ title }}!
</h1>